Feat/add playbook reject old alert
SEKOIA-IO/Community pull request #49
Opened 2022-01-10 13:32 UTC by Thibault-MAL

Reject old alerts not updated for 1 year.

2022-01-10 15:33 UTC, gaelmuller requested changes
Ideally for template readibility you chose reorder nodes

2022-01-10 15:33 UTC, gaelmuller commented on playbooks/templates/Reject_old_alerts.json
> +    },
should probably be removed

2022-01-10 15:33 UTC, gaelmuller commented on playbooks/templates/Reject_old_alerts.json
> +  },
Not sure I understand the point here. What is the "End of the playbook" action ?

2022-01-13 09:22 UTC, Thibault-MAL commented
Close in favor of https://github.com/SEKOIA-IO/Community/pull/50

2022-01-13 09:22 UTC, closed without merging